name: Release Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        variant:
          - { name: "Non-KSU", KSU: "None", KSU_SUSFS: "false", KSU_MANUAL_HOOK: "false", LAST_BUILD: "false" }
          - { name: "KSUN-Only", KSU: "Next", KSU_SUSFS: "false", KSU_MANUAL_HOOK: "true", LAST_BUILD: "false" }
          - { name: "KSUN+SuSFS", KSU: "Next", KSU_SUSFS: "true", KSU_MANUAL_HOOK: "true", LAST_BUILD: "false" }
          - { name: "SUKISU-Only", KSU: "Suki", KSU_SUSFS: "false", KSU_MANUAL_HOOK: "false", LAST_BUILD: "false" }
          - { name: "SUKISU+SuSFS", KSU: "Suki", KSU_SUSFS: "true", KSU_MANUAL_HOOK: "true", LAST_BUILD: "true" }
    name: Build ${{ matrix.variant.name }} variant
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      KSU: ${{ matrix.variant.KSU }}
      KSU_SUSFS: ${{ matrix.variant.KSU_SUSFS }}
      KSU_MANUAL_HOOK: ${{ matrix.variant.KSU_MANUAL_HOOK }}
      LAST_BUILD: ${{ matrix.variant.LAST_BUILD }}
      BUILD_BOOTIMG: "true"
      TODO: "kernel"

  release:
    name: Create Unified Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_files

      - name: Extract variables from info.txt (Safe)
        run: |
          # Find the info.txt file
          info_file=$(find release_files -name "info.txt" -type f | head -1)

          if [[ -f "$info_file" ]]; then
            echo "Found info.txt at: $info_file"

            # Extract variables safely without using functions.sh
            while IFS='=' read -r key value; do
              # Skip empty lines and comments
              [[ -z "$key" || "$key" =~ ^#.*$ ]] && continue

              # Clean up whitespace
              key=$(echo "$key" | xargs)
              value=$(echo "$value" | xargs)

              # Validate that we have both key and value
              if [[ -n "$key" && -n "$value" ]]; then
                echo "Setting: $key=$value"
                echo "$key=$value" >> $GITHUB_ENV
              fi
            done < "$info_file"

            echo "Variables extracted successfully"
          else
            echo "Warning: info.txt not found in artifacts"
            echo "Available files:"
            find release_files -type f -name "*.txt" || echo "No .txt files found"

            # Set default values to prevent pipeline failure
            echo "KERNEL_NAME=SuiKernel" >> $GITHUB_ENV
            echo "LINUX_VERSION=5.10" >> $GITHUB_ENV
            echo "KSU_NEXT_VERSION=unknown" >> $GITHUB_ENV
            echo "SUKISU_VERSION=unknown" >> $GITHUB_ENV
            echo "SUSFS_VERSION=unknown" >> $GITHUB_ENV
            echo "RELEASE_REPO=LoggingNewMemory/SuiKernel-Releases" >> $GITHUB_ENV

            echo "Using default values to continue release process"
          fi

      - name: Generate release tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
            # Get the latest tag, handle case where no tags exist
            LATEST_TAG=$(gh api repos/$RELEASE_REPO/tags --jq '.[0].name' 2>/dev/null || echo "")

            # Handle case when $LATEST_TAG doesn't contain $KERNEL_NAME or is empty
            if [[ -z "$LATEST_TAG" ]] || ! echo "$LATEST_TAG" | grep -q "$KERNEL_NAME"; then
                RELEASE_TAG="$KERNEL_NAME-HSKY1"
            else
                RELEASE_TAG="$LATEST_TAG"
                # Check if it's already using HSKY format
                if echo "$RELEASE_TAG" | grep -q "HSKY"; then
                    # Extract current HSKY number and increment
                    CURRENT_NUM=$(echo "$RELEASE_TAG" | sed -n 's/.*HSKY\([0-9]\+\).*/\1/p')
                    if [[ -n "$CURRENT_NUM" ]]; then
                        NEW_NUM=$((CURRENT_NUM + 1))
                        RELEASE_TAG="$KERNEL_NAME-HSKY$NEW_NUM"
                    else
                        # Fallback if extraction fails
                        RELEASE_TAG="$KERNEL_NAME-HSKY1"
                    fi
                else
                    # Convert from old r format to new HSKY format
                    # Extract the number from old format (e.g., SuiKernel-r5 -> 5)
                    OLD_NUM=$(echo "$RELEASE_TAG" | sed -n 's/.*-r\([0-9]\+\).*/\1/p')
                    if [[ -n "$OLD_NUM" ]]; then
                        # Start HSKY numbering from the old number + 1
                        NEW_NUM=$((OLD_NUM + 1))
                        RELEASE_TAG="$KERNEL_NAME-HSKY$NEW_NUM"
                    else
                        # Fallback if we can't extract the old number
                        RELEASE_TAG="$KERNEL_NAME-HSKY1"
                    fi
                fi
            fi

            echo "Release tag: $RELEASE_TAG"
            echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Upload All Builds to release repo
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.RELEASE_REPO }}
          name: ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          prerelease: true
          files: release_files/**/*
          body: |
            ## 📢 ${{ env.RELEASE_TAG }} Builds
            -> Linux ${{ env.LINUX_VERSION }} (android12-5.10-lts)
            -> KSUNext ${{ env.KSU_NEXT_VERSION }}
            -> SukiKSU ${{ env.SUKISU_VERSION }}
            -> SUSFS ඞ ${{ env.SUSFS_VERSION }}

            #### ✍️ Notes
            -> This kernel only for GKI android12-5.10 device
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Send notification to TG (Safe)
        run: |
          # Only send notification if we have the required secrets
          if [[ -n "$TG_BOT_TOKEN" && -n "$TG_CHAT_ID" ]]; then
            # Simple curl-based notification instead of using functions.sh
            MESSAGE="📦 Release completed! [Click](https://github.com/${{ env.RELEASE_REPO }}/releases/tag/${{ env.RELEASE_TAG }})"

            curl -s -X POST "https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage" \
              -d chat_id="$TG_CHAT_ID" \
              -d text="$MESSAGE" \
              -d parse_mode="Markdown" \
              -d disable_web_page_preview=true || echo "Telegram notification failed, but continuing..."
          else
            echo "Telegram secrets not available, skipping notification"
          fi
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}